apiVersion: apps/v1
kind: Deployment
metadata:
  name: scalesserver
spec:
  selector:
    matchLabels:
      run: scalesserver
  replicas: 1
  template:
    metadata:
      labels:
        run: scalesserver
    spec:
      containers:
      - name: scalesserver
        image: ghcr.io/iljarotar/scalesserver:latest
        command:
          - /scalesserver
        args:
          - --max-range=16
          - --max-num=16
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 16Mi
---
apiVersion: v1
kind: Service
metadata:
  name: scalesserver
  labels:
    run: scalesserver
spec:
  ports:
  - port: 8080
  selector:
    run: scalesserver
