apiVersion: batch/v1
kind: Job
metadata:
  name: locust
spec:
  template:
    spec:
      containers:
      - name: locust
        image: ghcr.io/iljarotar/hybrid-scaler-testing:latest
        command: ["./run.sh"]
      restartPolicy: Never
      resources:
        limits:
          cpu: 1
        requests:
          cpu: 100m
  backoffLimit: 4

