apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust
spec:
  selector:
    matchLabels:
      run: locust
  replicas: 1
  template:
    metadata:
      labels:
        run: locust
    spec:
      containers:
      - name: locust
        image: ghcr.io/iljarotar/hybrid-scaler-testing:latest
        command:
        - ./run.sh
        - http://scalesserver:8080
