apiVersion: scaling.autoscaling.custom/v1
kind: HybridScaler
metadata:
  name: scalesserver
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scalesserver
  minReplicas: 1
  maxReplicas: 10
  resourcePolicy:
    targetUtilization:
      cpu: 50
      memory: 50
    minAllowed:
      cpu: 50m
      memory: 16Mi
    maxAllowed:
      cpu: 2
      memory: 1Gi
    limitsToRequestsRatioCPU: 2
    limitsToRequestsRatioMemory: 2
  learningType: qLearning
  interval: 15
  qLearningParams:
    learningRate: 100m
    discountFactor: 500m
    epsilon: 100m
    cpuCost: 4G
    memoryCost: 1
    underprovisioningPenalty: 2
