apiVersion: batch/v1
kind: CronJob
metadata:
  name: locust
spec:
  schedule: "0 3,9,15,21 * * *"
  ttlSecondsAfterFinished: 3600
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: locust
            image: ghcr.io/iljarotar/hybrid-scaler-testing:latest
            imagePullPolicy: Always
            command:
            - ./run.sh
            - http://scalesserver:8080
          restartPolicy: OnFailure

